using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace ChatServerCore.Repository.Model
{
    public class ChatUser
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }  
       
        public string Id { get; set; }  
       
        public string UserName { get; set; } = string.Empty;

        public string NickName { get; set; } = string.Empty;

        public string Mobile { get; set; } = string.Empty;

        public DateTime UpdatedOn { get; set; } = DateTime.Now;

        public DateTime CreatedOn { get; set; } = DateTime.Now;
      
    }
}
